### ISSUE TITLE
Check for 'default' when aeon_request_repository_mappings is used

### ISSUE THREAD

**Issue by mark-cooper** [smoil/aeon_requests#1]
Looking good!

Peeking at:

https://github.com/smoil/aeon_requests/blob/master/public/controllers/aeon_requests_controller.rb#L168-L169

If a site has added mappings but overlooked / left out the 'default' and the repo_code is not present then it will error out. Because the 'default' is (sort of) required it might make sense to look for that key in `plugin_init.rb`.

Something like:

``` ruby
if AppConfig[:aeon_request_repository_mappings].any? and not AppConfig[:aeon_request_repository_mappings].has_key? "default"
  # raise an exception "Sorry, read the docs again, default is required =)" ...
end
```

Having said that it might be preferable to break it out of the hash entirely and create a `aeon_request_repository_default` variable (required) with explanation: the default Aeon repository code for requests made to Aeon. Will be used for all requests that do not match a mapping in aeon_request_repository_mappings (or always if no mappings are supplied).

**Comment by smoil** [comment]
@mark-cooper thanks for shining a light on this.  I've went ahead and moved the default mapping option to its own setting (easier to understand and more flexible).

``` ruby
def determine_site_from_repo_code(repo_code)
  if AppConfig[:aeon_request_repository_mappings].present?
    AppConfig[:aeon_request_repository_mappings][repo_code] ||
      AppConfig[:aeon_request_repository_mappings_default]
  else
    repo_code
  end
end
```

A failed mapping lookup will return `nil`, which will lead to the usage of the default value.
